### ISSUE TITLE
apiaxle doesn't install on node v6.3.1 npm  v3.10.6 gcc 4.8.4 ubuntu 14.04

### ISSUE THREAD

**Issue by g-borgulya** [apiaxle/apiaxle#88]
I tried first with

```npm install apiaxle-api```

but it failed exactly for the same reason as #81 
As I saw the fix on the development branch #82 , so I downloaded the source and compiled with make.
But when it comes to ```npm install <folder-to-apiaxle-base>``` it fails still:

```bash
In file included from ../src/libxmljs.h:7:0,
                 from ../src/libxmljs.cc:7:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1939:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/gulyas/.node-gyp/6.3.1/include/node/v8.h:2735): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
../src/libxmljs.cc: In function ‘void libxmljs::xmlMemFreeWrap(void*)’:
../src/libxmljs.cc:56:24: warning: ‘static bool v8::V8::IsDead()’ is deprecated (declared at /home/gulyas/.node-gyp/6.3.1/include/node/v8.h:8462): Use isolate version [-Wdeprecated-declarations]
     if (v8::V8::IsDead())
                        ^
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory `/home/gulyas/Projects/gli-solutions/apiaxle/apiaxle-user/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-77-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gulyas/Projects/gli-solutions/apiaxle/apiaxle-user/node_modules/libxmljs
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
apiaxle-user@1.0.0 /home/gulyas/Projects/gli-solutions/apiaxle/apiaxle-user
├── date-utils@1.2.21  extraneous
├── express@3.2.6  extraneous
├── hiredis@0.4.1  extraneous
├── lodash@1.2.1  extraneous
├── redis@0.10.3  extraneous
├── request@2.20.0  extraneous
└── scarf@0.0.10  extraneous

npm WARN apiaxle-user@1.0.0 No description
npm WARN apiaxle-user@1.0.0 No repository field.
npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "../apiaxle/base"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

[npm-debug.log.zip](https://github.com/apiaxle/apiaxle/files/412472/npm-debug.log.zip)

**Comment by g-borgulya** [comment]
it seems the problem is with `js2xml`, as it tries to install `libxmljs@0.14.3` which fails. I haven't tried this but it seems js2xml has to be compiled also from source to have the right dependencies. (It might not be sufficient still.)

Any chance to update the npm repository to get `npm install apiaxle-api` work correctly?

**Comment by g-borgulya** [comment]
(Compiling js2xml manually gets things further but it's not enough to install the apiaxle-api . Gave up at this point... )

**Comment by fillup** [comment]
@g-borgulya you said you gave up on this, but I wanted to check if you ever figured it out? We've started to actively maintain and enhance apiaxle again and we'll be looking to work on version upgrades to support newer versions of node and I'm sure we'll run into this problem when we do. We have a PR open now, #89, for this but I haven't tested it yet.

**Comment by g-borgulya** [comment]
@fillup I gave up, sorry...
